function [Ia_pu,Il_pu,Ea_pu,Z_pu,Fp_pu] = calc_gs_pu( ...
    Ia_ref, ...
    Il_ref, ...
    Ea_ref, ...
    Z_ref, ...
    Fp_ref, ...
    Ia, ...
    Il, ...
    Ea, ...
    Z, ...
    Fp)
    %% Corrente de Armadura
    Ia_pu = Ia/Ia_ref;

    %% Corrente de Linha
    Il_pu = Il/Il_ref;

    %% Tensão Induzida
    Ea_pu = Ea/Ea_ref;

    %% Impedância
    Z_pu = Z/Z_ref;
    
    %% Fator de Potência?
    Fp_pu = Fp/Fp_ref;

end